# Generated by Django 5.0.2 on 2024-02-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Fund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "strategy",
                    models.CharField(
                        choices=[
                            ("LSE", "Long/Short Equity"),
                            ("GLM", "Global Micro"),
                            ("ARB", "Arbitrage"),
                        ],
                        max_length=3,
                    ),
                ),
                ("aum", models.PositiveIntegerField()),
                ("inception_date", models.DateField()),
            ],
        ),
    ]
