services:
  api: &api
    build:
      context: .
      dockerfile: Dockerfile
    image: fund
    command: poetry run python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - '8000:8000'
    restart: unless-stopped
